### ISSUE TITLE
Missing setup for AppBundle & Activity

### ISSUE THREAD

**Issue by augustogoncalves** [JohnOnSoftware/design.automation-nodejs-revit.file.upgrader#12]
Ideally your sample should auto-setup (AppBundle & Activity), assuming the bundle ZIP is on a specific folder (see #9 )

If not possible, review the README to include clear instructions on how to set up and JSON required to create AppBundle & Activity.

What is described [here](https://github.com/Autodesk-Forge/design.automation-nodejs-revit.file.upgrader#main-backend-api-used) is not clear ....

As a reference, see how I [EnsureAppBundle](https://github.com/Autodesk-Forge/design.automation-csharp-revit.check.issues/blob/master/web/Controllers/DesignAutomation4Revit.cs#L211) and EnsureActivity exists at my .NET sample.

**Comment by JohnOnSoftware** [comment]
fixed by https://github.com/Autodesk-Forge/design.automation-nodejs-revit.file.upgrader/commit/17706c8effe922148fb2e993545ac1e6e8a9de32
