### ISSUE TITLE
Revit plugin needs folder structure and post-build event

### ISSUE THREAD

**Issue by augustogoncalves** [JohnOnSoftware/design.automation-nodejs-revit.file.upgrader#9]
See learnforge tutorial, please use same structure

As a sample, when we build the plugin, it should prepare the ZIP and place on the folder where it can be used by your app

**Comment by JohnOnSoftware** [comment]
fixed by https://github.com/Autodesk-Forge/design.automation-nodejs-revit.file.upgrader/commit/17706c8effe922148fb2e993545ac1e6e8a9de32
